import mongoose from "mongoose";

const timetableSlotSchema = new mongoose.Schema({
  day: {
    type: String,
    enum: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
    required: true,
  },
  timeSlot: {
    type: String,
    required: true, // e.g., "08:00-09:00"
  },
  subject: {
    type: String,
    required: true,
  },
  teacherId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: "Teacher",
    required: false, // Can be null if no teacher assigned
  },
  teacherStatus: {
    type: String,
    enum: ["assigned", "unassigned"],
    default: "assigned",
  },
  room: {
    type: String,
    default: "",
  },
});

const timetableSchema = new mongoose.Schema(
  {
    grade: {
      type: Number,
      required: true,
    },
    section: {
      type: String,
      required: true,
    },
    stream: {
      type: String,
      default: null, // For Grades 12-13
    },
    term: {
      type: Number,
      required: true, // 1, 2, or 3
    },
    year: {
      type: Number,
      required: true,
    },
    slots: [timetableSlotSchema],
    autoGenerated: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

// Prevent duplicate timetables for same class/term/year
timetableSchema.index({ grade: 1, section: 1, stream: 1, term: 1, year: 1 }, { unique: true });

export default mongoose.models.Timetable || mongoose.model("Timetable", timetableSchema);



